target("file-system")
set_kind("shared")
set_targetdir(path.join(os.projectdir(), "lib"))
add_files("src/*.cpp")
add_headerfiles("include/*.h", "include/*.hpp")
add_includedirs("include", { public = true })
add_packages("openssl", { public = true })
add_syslinks("crypto", "ssl", { public = true })
