target("http")
set_languages("c++20")
set_kind("shared")
set_targetdir(path.join(os.projectdir(), "lib"))
add_files("src/*.cpp")
add_headerfiles("include/(**.h)")
add_includedirs("include", { public = true })
add_deps("ctcpserver")
on_load(function(target)
	target:set("installdir", path.join(os.projectdir(), "lib"))
end)
