target("tcp_client")
set_kind("shared")
set_targetdir(path.join(os.projectdir(), "lib"))
add_headerfiles("include/(**.h)", "include/(**.hpp)")
add_includedirs("include", { public = true })
add_files("src/*.cpp")
add_deps("logger", "net", "thread-pool")
