target("file-send-process")
    set_kind("binary")
    set_targetdir(path.join(os.projectdir(), "bin"))
    add_files("main.cpp")
    add_deps("logger", "net", "thread-pool", "tcp_client", "file-transfer")
    add_ldflags("-Wl,-rpath," .. path.join(os.projectdir(), "lib"), "-Wl,--disable-new-dtags", {force = true})
