target("websocket")
set_kind("shared")
set_languages("c++20")
set_targetdir(path.join(os.projectdir(), "lib"))
add_files("src/*.cpp")
add_headerfiles("include/(**.h)", "include/(**.hpp)")
add_includedirs("include", { public = true })
add_includedirs("../http/include")
add_syslinks("crypto", { public = true })
add_deps("tcp_server")
add_links("http")
add_linkdirs(path.join(os.projectdir(), "lib"))
